### ISSUE TITLE
Badger wallet doesn't show SLP tokens

### ISSUE THREAD

**Issue by andersrh** [Bitcoin-com/badger#29]
**Describe the bug**
Badger wallet does not show tokens. I have tried to create tokens in the SLP version of Electron Cash and send them to Badger wallet, but they are not shown. Tried to create a new account in Badger, still no success. I also tried to reinstall badger and import my account.

**To Reproduce**
1. Create token in Electron Cash.
2. Send them to badger
3. Look in the left menu

**Expected behavior**
I would see my tokens in the left menu.

**Screenshots**
![billede](https://user-images.githubusercontent.com/20405991/51677232-32abe080-1fd9-11e9-8a19-82a00f5e91cc.png)

**Browser details (please complete the following information):**
 - OS: Ubuntu Linux 18.10
 - Browser: tested in Firefox 64.0 and Chromium 71.0.3578.98
 - Badger Version 0.1.3

**Comment by cgcardona** [comment]
This has been fixed in v0.1.14

**Comment by pvyhnal-generalbytes** [comment]
it still doesn't work for me in chrome and android version. It has 8 confirmations, I can see the balance on https://simpleledger.info/ but not in the wallet
